// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"uav/biz/conf"
	"uav/biz/infra"
	"uav/biz/mw/cors"
	"uav/biz/router"
)

func main() {
	conf.Init()
	infra.InitMysql() // 初始化mysql
	infra.InitRedis() // 初始化redis
	h := server.Default(server.WithHostPorts(conf.Conf.System.Port))
	h.Use(cors.CorsMw()) // 使用跨域中间件
	router.Register(h)   // 注册路由
	h.Spin()
}
